### ISSUE TITLE
transfer to thephpleague organization

### ISSUE THREAD

**Issue by glensc** [lossendae/commonmark-task-lists#2]
seems this package is abandoned, no support (at least) from may 2018, there's PR to update to 0.18 and still not merged: https://github.com/lossendae/commonmark-task-lists/pull/1

and it even then has a fatal bug: https://github.com/lossendae/commonmark-task-lists/pull/1#issuecomment-508009090

i've created issue in thephpleague https://github.com/thephpleague/commonmark-extras/issues/22 so they can give their feedback.

cc @colinodell @sanpii @lossendae @danhunsaker

**Comment by lossendae** [comment]
Hello, as specified in the common mark issue, i'll archive this project and add a link to their own extension. Thank you.
